# Generated by Django 4.1 on 2022-09-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_product_stock'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartitem',
            new_name='cart_item',
        ),
    ]
